### PR TITLE
Fix krew on Apple silicon

### LINKED ISSUE #836: krew broken
```
2023/01/08 00:04:13 Looking up version for krew
2023/01/08 00:04:23 Found: v0.4.3
Downloading: https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-.tar.gz
Error: incorrect status for downloading tool: 404
```
## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [ ] No

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## If requesting a CLI for "arkade get"

How many downloads does this tool have? Check at: 

https://somsubhra.github.io/github-release-stats/

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

* What arkade version is this?

```
arkade version
```

### PR DESCRIPTION
**Pull request by rgee0**
Signed-off-by: Richard Gee <richard@technologee.co.uk>

## Description
Adds `arm64` for `darwin` into the tool templates as #836 looks like a possible Apple silicon gap.
There was a `darwin_arm64` entry under the `ming` path in the template, so the `or` has been added in there too.

## Motivation and Context
- [x] I have raised an issue to propose this change, which has been given a label of `design/approved` by a maintainer

Might fix #836 - would have been more certain had @bayeslearner completed the issue template.

## How Has This Been Tested?
Added unit tests but haven't been able to test as I don't have apple silicon.  Maybe @bayeslearner can help?  [Here's how](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md#test-other-peoples-prs)

## Are you a GitHub Sponsor yet (Yes/No?)

- [ ] Yes
- [x] No

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [ ] I have updated the list of tools in README.md if (required) with `./arkade get -o markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

File: pkg/get/get_test.go [hunk 1]
```diff
@@ -3312,38 +3312,56 @@ func Test_DownloadKrew(t *testing.T) {
 		{
 			os:      "darwin",
 			arch:    arch64bit,
-			version: "v0.4.2",
-			url:     `https://github.com/kubernetes-sigs/krew/releases/download/v0.4.2/krew-darwin_amd64.tar.gz`,
+			version: "v0.4.3",
```
Comment (rgee0) [inline pkg/get/get_test.go:3315]: Bump the version to current krew release

File: pkg/get/get_test.go [hunk 2]
```diff
@@ -3354,7 +3372,7 @@ func Test_DownloadKrew(t *testing.T) {
 				t.Fatal(err)
 			}
 			if got != tc.url {
-				t.Errorf("want: %s, got: %s", tc.url, got)
+				t.Errorf("want: %s for %s on %s, got: %s", tc.url, tc.os, tc.arch, got)
```
Comment (rgee0) [inline pkg/get/get_test.go:3375]: Added additional detail here because where multiple OS and Arch combinations target a single URI it is challenging to find the failing test case.

**Comment by rgee0** [comment]
Url check failing on a unrelated tool:

```
url_checker_test.go:51: Error with HTTP HEAD for kail, https://github.com/boz/kail/releases/download/v0.16.1/kail_0.16.1_linux_amd64.tar.gz: status code: 404
```

File: pkg/get/tools.go [hunk 3]
```diff
@@ -1139,7 +1139,7 @@ https://releases.hashicorp.com/{{.Name}}/{{.Version}}/{{.Name}}_{{.Version}}_{{$
 	{{$os = "windows"}}
 	{{- end -}}
 
-	{{.Version}}/{{.Name}}_{{.VersionNumber}}_{{$os}}_{{$arch}}.tar.gz`,
+	{{.Version}}/{{.Name}}_v{{.VersionNumber}}_{{$os}}_{{$arch}}.tar.gz`,
```
Comment (rgee0) [inline pkg/get/tools.go:1142]: Added this in a later commit after the url checker tests failed in the CI.  Kail seem to have changed the asset names from [v0.16.0](https://github.com/boz/kail/releases/tag/v0.16.0)

File: pkg/get/get_test.go [hunk 4]
```diff
@@ -3312,38 +3312,56 @@ func Test_DownloadKrew(t *testing.T) {
...
+			url:     `https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-windows_amd64.tar.gz`,
+		},
+		{
+			os:      "ming",
+			arch:    archARM64,
+			version: "v0.4.3",
+			url:     `https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-darwin_arm64.tar.gz`,
+		},
+		{
+			os:      "ming",
```
Comment (alexellis) [inline pkg/get/get_test.go:3361]: What's this entry for? Windows + MacOS 64-bit?

File: pkg/get/get_test.go [hunk 5]
```diff
@@ -3312,38 +3312,56 @@ func Test_DownloadKrew(t *testing.T) {
...
 			os:      "darwin",
 			arch:    arch64bit,
-			version: "v0.4.2",
-			url:     `https://github.com/kubernetes-sigs/krew/releases/download/v0.4.2/krew-darwin_amd64.tar.gz`,
+			version: "v0.4.3",
+			url:     `https://github.com/kubernetes-sigs/krew/releases/download/v0.4.3/krew-darwin_amd64.tar.gz`,
 		},
 		{
 			os:      "darwin",
 			arch:    archARM64,
```
Comment (alexellis) [inline pkg/get/get_test.go:3320]: I think this test may have been wrong in the first place, since the value should be archDarwinARM64 from `uname` on MacOS M1

`Darwin am1.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 arm64`

cc @Jasstkn

Comment (Jasstkn) [reply pkg/get/get_test.go:3320]: yes, it should be `archDarwinARM64`.

File: pkg/get/get_test.go (hunk 4 above)
Comment (rgee0) [reply pkg/get/get_test.go:3361]: Yes, I meant to comment here: https://github.com/alexellis/arkade/pull/837/files#diff-6e1468cd6d67c262166efacb61ddf1e9dbb404be9ca1acd3ce0c2c2abc95a741R1031

To the effect that i didn't understand the darwin entry under ming but added the additional arch entry for consistency

**Review by alexellis — APPROVED** [review]
Approved
