### PR TITLE
fix: arkade get inletsctl on linux aarch64 and mingw

### LINKED ISSUE #922: bug: arkade get inletsctl fails in linux aarch64 and GitBash
arkade get `inletsctl` fails in linux aarch64 and mingw

Installing inletsctl in GitBash (WSL) downloads the .exe file but is unable to copy it into the bin folder.

## Current Behaviour
Downloads `inletsctl.exe` but the copy command fails because it is looking for `inletsctl.exe.exe`

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
Two ways to repro:

test-tool.sh
```
$ ./hack/test-tool.sh inletsctl
+ ./arkade get inletsctl --arch arm64 --os darwin --quiet
+ file .arkade/bin/inletsctl
/path/.arkade/bin/inletsctl: Mach-O 64-bit arm64 executable, flags:<|DYLDLINK|PIE>
+ rm /path/.arkade/bin/inletsctl
+ echo

+ ./arkade get inletsctl --arch x86_64 --os darwin --quiet
+ file /path/.arkade/bin/inletsctl
/path/.arkade/bin/inletsctl: Mach-O 64-bit x86_64 executable
+ rm /path/.arkade/bin/inletsctl
+ echo

+ ./arkade get inletsctl --arch x86_64 --os linux --quiet
+ file /path/.arkade/bin/inletsctl
/path/.arkade/bin/inletsctl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=6M_Wagl7j2oAMAhNLegz/ElId8XoAfS4FFgo3RTUH/vdJIc5Q5GK5NVWWpn_rm/YKO4s5vPb3kc4txX14QC, stripped
+ rm /path/.arkade/bin/inletsctl
+ echo

+ ./arkade get inletsctl --arch aarch64 --os linux --quiet
Error: CreateFile /path/arkade-3336224941/inletsctl: The system cannot find the file specified.
+ ./arkade get inletsctl --arch x86_64 --os mingw --quiet
Error: CreateFile /path/arkade-2784826040/inletsctl.exe.exe: The system cannot find the file specified.
```

arkade get inletsctl
```
$ arkade get inletsctl
Downloading: inletsctl
2023/06/04 17:26:34 Looking up version for inletsctl
2023/06/04 17:26:34 Found: 0.8.21
Downloading: https://github.com/inlets/inletsctl/releases/download/0.8.21/inletsctl.exe.tgz
path/arkade-3701239706/inletsctl.exe.tgz written.
2023/06/04 17:26:35 Looking up version for inletsctl
2023/06/04 17:26:35 Found: 0.8.21
2023/06/04 17:26:36 Extracted: /path/arkade-3701239706/inletsctl.exe.exe
2023/06/04 17:26:36 Copying /path/arkade-3701239706/inletsctl.exe.exe to C:\Users\X/.arkade/bin/inletsctl.exe
Error: CreateFile /path/arkade-3701239706/inletsctl.exe.exe: The system cannot find the file specified.
```

## Your Environment

* What Kubernetes distribution are you using?

```
kubectl version
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
uname -a

cat /etc/os-release
```

* What arkade version is this?

```
arkade version
```

### PR DESCRIPTION
**Pull request by joebowbeer**
## Description
Fix `arkade get inletsctl` on linux aarch64 and mingw

## Motivation and Context
Fixes #922 

## How Has This Been Tested?
make e2e
```
    --- PASS: Test_CheckTools/Download_of_inletsctl (0.62s)
PASS
        github.com/alexellis/arkade/pkg/get     coverage: 54.9% of statements
ok      github.com/alexellis/arkade/pkg/get     7.964s  coverage: 54.9% of statements
```

./hack/test-tool.sh inletsctl
```
+ ./arkade get inletsctl --arch arm64 --os darwin --quiet
+ file /c/Users/joebo/.arkade/bin/inletsctl
/c/Users/joebo/.arkade/bin/inletsctl: Mach-O 64-bit arm64 executable, flags:<|DYLDLINK|PIE>
+ rm /c/Users/joebo/.arkade/bin/inletsctl
+ echo

+ ./arkade get inletsctl --arch x86_64 --os darwin --quiet
+ file /c/Users/joebo/.arkade/bin/inletsctl
/c/Users/joebo/.arkade/bin/inletsctl: Mach-O 64-bit x86_64 executable
+ rm /c/Users/joebo/.arkade/bin/inletsctl
+ echo

+ ./arkade get inletsctl --arch x86_64 --os linux --quiet
+ file /c/Users/joebo/.arkade/bin/inletsctl
/c/Users/joebo/.arkade/bin/inletsctl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=6M_Wagl7j2oAMAhNLegz/ElId8XoAfS4FFgo3RTUH/vdJIc5Q5GK5NVWWpn_rm/YKO4s5vPb3kc4txX14QC, stripped
+ rm /c/Users/joebo/.arkade/bin/inletsctl
+ echo

+ ./arkade get inletsctl --arch aarch64 --os linux --quiet
+ file /c/Users/joebo/.arkade/bin/inletsctl
/c/Users/joebo/.arkade/bin/inletsctl: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=3NsRKwpuEEkZC61LBu96/PL2wjtAOPiHovxsxmsJD/cK_e0dZ-RARc9Cap2aQl/KECauLt3s1gFJHPXkfUo, stripped
+ rm /c/Users/joebo/.arkade/bin/inletsctl
+ echo

+ ./arkade get inletsctl --arch x86_64 --os mingw --quiet
+ file /c/Users/joebo/.arkade/bin/inletsctl.exe
/c/Users/joebo/.arkade/bin/inletsctl.exe: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
+ rm /c/Users/joebo/.arkade/bin/inletsctl.exe
+ echo
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Documentation

- [ ] I have updated the list of tools in README.md if (required) with `./arkade get --format markdown`
- [ ] I have updated the list of apps in README.md if (required) with `./arkade install --help`

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/arkade/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

File: pkg/get/tools.go [hunk 1]
```diff
@@ -463,21 +463,23 @@ https://storage.googleapis.com/kubernetes-release/release/{{.Version}}/bin/{{$os
 {{- end -}}
 https://github.com/inlets/inletsctl/releases/download/{{.Version}}/{{$fileName}}`,
 			BinaryTemplate: `{{ if HasPrefix .OS "ming" -}}
-{{.Name}}.exe
+{{.Name}}
```
Comment (alexellis) [inline pkg/get/tools.go:466]: If these needed to change, why didn't the unit tests also get changed?

If there are none, could you add them please?

Comment (joebowbeer) [reply pkg/get/tools.go:466]: The URLs expected by the unit tests did not change.

What did change is the expected name of the executable, and there are no unit tests for that anywhere, AFAICT, right?

**Comment by joebowbeer** [comment]
@alexellis I enhanced the unit test to verify that the name in BinaryTemplate is consistent with the name in URLTemplate.

This test fails in the main branch, and is fixed by the change to tools.go

File: pkg/get/get_test.go [hunk 2]
```diff
@@ -810,7 +812,18 @@ func Test_DownloadInletsctl(t *testing.T) {
...
 		}
 		if got != tc.url {
-			t.Fatalf("want: %s, got: %s", tc.url, got)
+			t.Errorf("for %s/%s, want: %q, but got: %q", tc.os, tc.arch, tc.url, got)
+		}
+		name, err := GetBinaryName(tool, tc.os, tc.arch, tc.version)
+		if err != nil {
+			t.Fatal(err)
+		}
+		// Remove the tgz and possible exe extensions from the url base name
```
Comment (alexellis) [inline pkg/get/get_test.go:821]: Hmm. this p

Comment (joebowbeer) [reply pkg/get/get_test.go:821]: Note that the changes that are needed to fix getting inletsctl only affect the Name in its BinaryTemplate.

This test, which fails prior to my changes and succeeds after, verifies that the Name in the BinaryTemplate is consistent with the base fileName in the URLTemplate.

The complication that makes this more difficult to explain is that the `.exe` extension is conditionally added in decompress.

Do you think `arkade get inletsctl` is not currently broken? tool-test.sh has two failures. Or that it is not fixed by my changes?

Comment (alexellis) [reply pkg/get/get_test.go:821]: Why are we doing `nameFromUrl := strings.Split(filepath.Base(tc.url), ".")[0]`?

It wasn't clear in isolation.

Now I think I get it.. you're trying to infer the name from the URL - but that may not always be the case.

We may want a new value in the test struct i.e. `wantBinaryName`?

Comment (joebowbeer) [reply pkg/get/get_test.go:821]: I started by adding a binary _base_ name to the test struct but that didn't seem to help, or at least not carry its weight, imo. It was just replicating fileName from the URL, without exe.

I don't think this can be tested more effectively without modeling what the tgz file contains and what the decompress function does.

In the case of inletsctl, maybe it's possible to eliminate one of the templates? That would eliminate the original problem of them being out of sync.

**Comment by joebowbeer** [comment]
@alexellis I added an optional binary base name string to the test struct.

This permits more direct testing of the value in the inletsctl unit test.

By the way, I notice that the for loop can be hoisted out of most of the tests:

```
	for _, tc := range tests { /* ... */ }
```

I can do that in a subsequent PR if you're interested.

**Comment by alexellis** [comment]
> By the way, I notice that the for loop can be hoisted out of most of the tests:

Could you show me a diff in a comment?

```diff
+ loop
- no loop needed
```

**Comment by joebowbeer** [comment]
@alexellis this PR fixes `arkade get inletsctl` on linux aarch64 and mingw, and adds a BinaryTemplate unit test.

I created a new PR for that hoists the test runner for loop in order to remove 1000 duplicated lines: #932

**Review by alexellis — APPROVED** [review]
Approved
