### PR TITLE
Fixes #98: Add stable repo for grafana

### LINKED ISSUE #98: Error installing Grafana
## Expected Behaviour

Install Grafana

## Current Behaviour

Installation fails

## Possible Solution

Verifying the 'stable' repo for grafana

## Steps to Reproduce (for bugs)

1. install arkade
2. run 'arkade install grafana'

## Your Environment

* What Kubernetes distribution are you using?
```
k3s 1.17.2
```
```
kubectl version
1.18
```

* Operating System and version (e.g. Linux, Windows, MacOS):

```
cat /etc/os-release
VERSION="18.04.4 LTS (Bionic Beaver)"
```

* What arkade version is this?

```
arkade version
0.2.8
```

### PR DESCRIPTION
**Pull request by aidun**
Fixes #98: Add stable repo for grafana

## Description

Add the `addHelmRepo` function to add stable ( https://kubernetes-charts.storage.googleapis.com ) Helm repository.

## Motivation and Context

#98 

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

```
helm repo remove stable
k3d create
./arkade install grafana
helm repo list
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

- [x] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

File: cmd/apps/grafana_app.go [hunk 1]
```diff
@@ -56,6 +56,11 @@ func MakeInstallGrafana() *cobra.Command {
 			return err
 		}
 
+		err = addHelmRepo("stable", "https://kubernetes-charts.storage.googleapis.com", true)
+		if err != nil {
+			return err
```
Comment (alexellis) [inline cmd/apps/grafana_app.go:61]: Are you sure this should return? What if it's already there and you run this twice in a row?

Comment (aidun) [reply cmd/apps/grafana_app.go:61]: I copied it from the helm Nginx app, as you said, but I tested it and you can add it multiple
times without an error. This should work.

Comment (alexellis) [reply cmd/apps/grafana_app.go:61]: Perfect. Thank you
