### PR TITLE
Fix the path on loki helm install

### LINKED ISSUE #132: Bug with Loki app prevents installation
Bug with Loki app prevents installation

## Expected Behaviour

To install loki

## Current Behaviour

```
"loki/loki-stack" has been added to your repositories
Error: repo loki not found
Error: exit code 1
```

The wrong repo name is added:

```
alex@nuc7:~$ ~/.arkade/bin/helm3/helm repo list
NAME           	URL                                             
inlets         	https://inlets.github.io/inlets-operator/       
jetstack       	https://charts.jetstack.io                      
stable         	https://kubernetes-charts.storage.googleapis.com
openfaas       	https://openfaas.github.io/faas-netes/          
traefik        	https://containous.github.io/traefik-helm-chart 
loki/loki-stack	https://grafana.github.io/loki/charts   
```

## Steps to Reproduce (for bugs)

Run the following:

```
alex@nuc7:~$ arkade update
You can update arkade with the following:
# Remove cached versions of tools
rm -rf $HOME/.arkade
# For Linux/MacOS:
curl -SLfs https://dl.get-arkade.dev | sudo sh
# For Windows (using Git Bash)
curl -SLfs https://dl.get-arkade.dev | sh
# Or download from GitHub: https://github.com/alexellis/arkade/releases
Thanks for using arkade!
alex@nuc7:~$ rm -rf $HOME/.arkade
alex@nuc7:~$ curl -SLfs https://dl.get-arkade.dev | sudo sh
x86_64
Downloading package https://github.com/alexellis/arkade/releases/download/0.3.6/arkade as /tmp/arkade
Download complete.
Running with sufficient permissions to attempt to move arkade to /usr/local/bin
New version of arkade installed to /usr/local/bin
            _             _      
  __ _ _ __| | ____ _  __| | ___ 
 / _` | '__| |/ / _` |/ _` |/ _ \
| (_| | |  |   < (_| | (_| |  __/
 \__,_|_|  |_|\_\__,_|\__,_|\___|
Get Kubernetes apps the easy way
Version: 0.3.6
Git Commit: 3b6845bced66cecfd302f153792ae10052718596
alex@nuc7:~$ arkade install loki
2020/06/19 19:36:12 Client: x86_64, Linux
2020/06/19 19:36:12 User dir established as: /home/alex/.arkade/
https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz
/home/alex/.arkade/bin/helm3/linux-amd64 linux-amd64/
/home/alex/.arkade/bin/helm3/helm linux-amd64/helm
/home/alex/.arkade/bin/helm3/README.md linux-amd64/README.md
/home/alex/.arkade/bin/helm3/LICENSE linux-amd64/LICENSE
2020/06/19 19:36:14 extracted tarball into /home/alex/.arkade/bin/helm3: 3 files, 0 dirs (913.587256ms)
"loki/loki-stack" has been added to your repositories
Error: repo loki not found
Error: exit code 1
alex@nuc7:~$
```

## Context

The app is effectively broken.

### PR DESCRIPTION
**Pull request by Waterdrips**
Missing a split on the  "/" in chart name so we installed the chart as "loki/loki-stack" rather than loki.

Tested by removing all references to loki from my helm3 repo ls

then used `go build && ./arkade install loki" which worked.

Fixes #132 

Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

see above
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

- [ ] I have tested this on arm, or have added code to prevent deployment

### CODE REVIEW

File: pkg/helm/helm.go [hunk 1]
```diff
@@ -124,6 +124,11 @@ func AddHelmRepo(name, url string, update, helm3 bool) error {
 	if helm3 {
 		subdir = "helm3"
 	}
+
```
Comment (alexellis) [inline pkg/helm/helm.go:127]: Please add a comment here to explain what is happening? This didn't seem to be necessary for any of the other apps?

Comment (Waterdrips) [reply pkg/helm/helm.go:127]: sorry i missed updating this before the PR was merged,

Its done so we can use 1 generic name in the new LokiOptions -> Heml -> Repo -> Name section.
All the other apps pass in just the `char`t name, not `repo/chart` - this is backward compatible as other apps pass in the `chart` section only.
